### PR TITLE
Update OkHttp3 to v4.0

### PR DESCRIPTION
**Pull request by mattleibow**
Required PRs:
 - https://github.com/xamarin/XamarinComponents/pull/717
 - https://github.com/xamarin/XamarinComponents/pull/718

### CODE REVIEW

**Comment by 4brunu** [comment]
This would be awesome 👍 Any news on this?

**Comment by mattleibow** [comment]
Whoops, got so distracted with other cool libraries. Let me finish this up now that the dependencies are published.

**Comment by 4brunu** [comment]
Nice, all the tests passed 👍

**Comment by mattleibow** [comment]
merged and building for release :)

**Comment by mattleibow** [comment]
Publishing now. Will be up in about 20 minutes. Have fun. I'll update the rest in a bit.

**Comment by 4brunu** [comment]
One question, this add's support for which version of OkHttp? 4.0?
Can you please add support for the current last version [4.2.2](https://github.com/square/okhttp/releases/tag/parent-4.2.2)?
Thanks

**Pull request merged**
