### PR TITLE
Update OkHttp3 to 4.3.1 and logging-interceptor

### PR DESCRIPTION
**Pull request by antonioseric**
I update okhttp3 library and added OkHttp3.LoggingInterceptor with icon. But first [Xamarin.Kotlin.StdLib version 1.3.61](https://github.com/xamarin/XamarinComponents/pull/785 ) must be released since OkHttp3 v4.3.1 has [dependency of kotlin-stdlib 1.3.61 ](https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp/4.3.1)

### CODE REVIEW

**Comment by antonioser** [comment]
this also solves #62

**Comment by 4brunu** [comment]
Do you think it would be possible to upgrade okhttp to version 4.4.0?
https://github.com/square/okhttp/releases/tag/parent-4.4.0
Thanks 😊

**Comment by antonioseric** [comment]
@4brunu before upgrading this PR is needed to be accepted https://github.com/xamarin/XamarinComponents/pull/785

**Comment by 4brunu** [comment]
Now that https://github.com/xamarin/XamarinComponents/pull/785 is merged, could this PR be merged?
Thanks

**Comment by antonioser** [comment]
NuGet package is not jet published https://www.nuget.org/packages/Xamarin.Kotlin.StdLib/

**Comment by mattleibow** [comment]
@antonioseric  I merged your PR in https://github.com/xamarin/XamarinComponents

Thanks for that! I never really get time to update my own packages, so if it is in the shared repo, then anyone can update/merge/release.
Thanks again!

**Comment by antonioseric** [comment]
I will update packages at least copy this PR to XamarinComponents. so expect more PR coming soon

**Comment by mattleibow** [comment]
Yay! Thanks!

**Pull request closed without merging**
